# app.py
import streamlit as st

def mock_trae_agent(code, language):
    """Simulates Trae AI's test generation for demo purposes"""
    if "python" in language.lower():
        return f"""# Generated by Trae AI (Mock)
import pytest

def test_add():
    # Test positive numbers
    assert {code.split('(')[0]}(2, 3) == 5
    
    # Test negative numbers
    assert {code.split('(')[0]}(-1, -1) == -2
    
    # Test zero
    assert {code.split('(')[0]}(0, 0) == 0
"""
    else:
        return f"""// Generated by Trae AI (Mock)
test('Sample Test', () => {{
  expect(1 + 1).toBe(2);
}});
"""

# Streamlit UI
st.title("🧪 One-Click Test Generator")
st.caption("Powered by Trae AI IDE")

code = st.text_area("Paste your code here:", height=200, 
                   placeholder="def add(a, b):\n    return a + b")
language = st.selectbox("Select language:", ["Python (pytest)", "JavaScript (Jest)"])

if st.button("Generate Tests"):
    if code.strip():
        st.code(mock_trae_agent(code, language), 
               language="python" if "python" in language.lower() else "javascript")
    else:
        st.error("Please enter code first!")